<?php

define( "YOUTUBE_IMPORTYOUTUBE_SECONDLINE_NAME", 'Import Youtube YouTube Importer' );
define( "YOUTUBE_IMPORTYOUTUBE_SECONDLINE_NAME_SHORT", 'Import Youtube' );
define( "YOUTUBE_IMPORTER_IMPORTYOUTUBE_ALIAS", 'youtube_importer_import_youtube' );
define( "YOUTUBE_IMPORTER_IMPORTYOUTUBE_PREFIX", 'youtube-importer-import_youtube' );

define( "YOUTUBE_IMPORTER_IMPORTYOUTUBE_SETTINGS_PERMISSION_CAP", 'manage_options' );
define( "YOUTUBE_IMPORTER_IMPORTYOUTUBE_FEED_PERMISSION_CAP", 'manage_options' );
define( "YOUTUBE_IMPORTER_IMPORTYOUTUBE_REST_API_PREFIX", YOUTUBE_IMPORTER_IMPORTYOUTUBE_PREFIX );
define( 'YOUTUBE_IMPORTER_IMPORTYOUTUBE_LANGUAGE_DIRECTORY', basename( dirname( YOUTUBE_IMPORTER_IMPORTYOUTUBE_BASE_FILE_PATH ) ) . '/languages/'  );

define( "YOUTUBE_IMPORTER_IMPORTYOUTUBE_POST_TYPE_IMPORT", 'importyoutube_import_yt' );